---
language: node_js
node_js:
  - "4"

sudo: false

# Chrome
#addons:
#  apt:
#    sources:
#      - google-chrome
#    packages:
#      - google-chrome-stable

cache:
  directories:
    - node_modules

env:
  - EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
# Chrome
#  - "export DISPLAY=:99.0"
#  - "sh -e /etc/init.d/xvfb start"
  - npm config set spin false
  - npm install -g npm@^3
  - npm install -g bower
# PhantomJS
  - npm install phantomjs-prebuilt

install:
  - npm install
  - bower install

script:
  - ember try:one $EMBER_TRY_SCENARIO test
