version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6-browsers
    working_directory: ~/gitzoom-web
    steps:
      - checkout
      - run: echo 'export PATH=~/gitzoom-web/node_modules/.bin:$PATH' >> $BASH_ENV
      - run:
          name: Install Bower
          command: sudo npm install -g bower
      - run:
          name: Yarn Install
          command: yarn install --non-interactive
      - run:
          name: Bower Install
          command: bower install
      - run:
          name: Run Tests
          command: yarn test
      - run:
          name: Deploy
          command: |
            if [[ "${CIRCLE_TAG}" =~ /v[0-9]+\.[0-9]+\.[0-9]+/ ]]; then
              ember deploy production
            fi
