defaults: &defaults
  docker:
    - image: circleci/node:6-browsers
      environment:
        JOBS: 2
  working_directory: ~/gitzoom-web

version: 2
jobs:
  install_dependencies:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-node-cache-{{ checksum "yarn.lock" }}
            - v1-node-cache-{{ .Branch }}
            - v1-node-cache
      - run:
          name: Yarn Install
          command: yarn install --non-interactive
      - save_cache:
          key: v1-node-cache-{{ checksum "yarn.lock" }}
          paths: "node_modules"
      - save_cache:
          key: v1-node-cache-{{ .Branch }}
          paths: "node_modules"
      - save_cache:
          key: v1-node-cache
          paths: "node_modules"
      - persist_to_workspace:
          root: .
          paths:
            - .

  lint_js:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Lint JS
          command: yarn run lint:js

  run_tests:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Tests
          command: yarn test

  deploy_production:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: echo 'export PATH=~/gitzoom-web/node_modules/.bin:$PATH' >> $BASH_ENV
      - run:
          name: Deploy
          command: ember deploy production

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - install_dependencies:
          filters:
            tags:
              only: /.*/
      - lint_js:
          requires:
            - install_dependencies
          filters:
            tags:
              only: /.*/
      - run_tests:
          requires:
            - install_dependencies
          filters:
            tags:
              only: /.*/
      - deploy_production:
          requires:
            - lint_js
            - run_tests
          filters:
            tags:
              only: /v[0-9]+\.[0-9]+\.[0-9]+/
            branches:
              ignore: /.*/
