defaults: &defaults
  docker:
    - image: circleci/node:6-browsers
      environment:
        JOBS: 2
  working_directory: ~/gitzoom-web

repo_key: &repo_key
  key: v1-repo-{{ checksum ".circle-sha" }}
npm_key: &npm_key
  key: v1-node-modules-{{ checksum "yarn.lock" }}
bower_key: &bower_key
  key: v1-bower-components-{{ checksum "bower.json" }}

save_sha: &save_sha
  name: Save SHA to File
  command: echo $CIRCLE_SHA1 > .circle-sha
add_npm_path: &add_npm_path
  name: Add NPM bin to PATH
  command: echo 'export PATH=~/gitzoom-web/node_modules/.bin:$PATH' >> $BASH_ENV

version: 2
jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - run:
          <<: *save_sha
      - save_cache:
          <<: *repo_key
          paths:
            - ~/gitzoom-web

  install_dependencies:
    <<: *defaults
    steps:
      - run:
          <<: *save_sha
      - restore_cache:
          <<: *repo_key
      - restore_cache:
          <<: *npm_key
      - restore_cache:
          <<: *bower_key
      - run:
          name: Install Bower
          command: sudo npm install -g bower
      - run:
          name: Yarn Install
          command: yarn install --non-interactive
      - run:
          name: Bower Install
          command: bower install
      - save_cache:
          <<: *npm_key
          paths:
            - ~/gitzoom-web/node_modules
      - save_cache:
          <<: *bower_key
          paths:
            - ~/gitzoom-web/bower_components

  run_tests:
    <<: *defaults
    steps:
      - run:
          <<: *save_sha
      - restore_cache:
          <<: *repo_key
      - restore_cache:
          <<: *npm_key
      - restore_cache:
          <<: *bower_key
      - run:
          <<: *add_npm_path
      - run:
          name: Run Tests
          command: yarn test

  deploy_production:
    <<: *defaults
    steps:
      - run:
          <<: *save_sha
      - restore_cache:
          <<: *repo_key
      - restore_cache:
          <<: *npm_key
      - restore_cache:
          <<: *bower_key
      - run:
          <<: *add_npm_path
      - run:
          name: Deploy Production
          command: ember deploy production

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - checkout_code:
          filters:
            tags:
              only: /.*/
      - install_dependencies:
          requires:
            - checkout_code
          filters:
            tags:
              only: /.*/
      - run_tests:
          requires:
            - install_dependencies
          filters:
            tags:
              only: /.*/
      - deploy_production:
          requires:
            - run_tests
          filters:
            tags:
              only: /v[0-9]+\.[0-9]+\.[0-9]+/
            branches:
              ignore: /.*/
