defaults: &defaults
  docker:
    - image: circleci/node:6-browsers
  working_directory: ~/gitzoom-web

save_sha: &save_sha
  name: Save SHA to File
  command: echo $CIRCLE_SHA1 > .circle-sha

version: 2
jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - run:
          <<: *save_sha
      - save_cache:
          key: v1-repo-{{ checksum ".circle-sha" }}
          paths:
            - ~/gitzoom-web

  install_dependencies:
    <<: *defaults
    steps:
      - run:
          <<: *save_sha
      - restore_cache:
          key: v1-repo-{{ checksum ".circle-sha" }}
      - restore_cache:
          key: v1-node-modules-{{ checksum "yarn.lock" }}
      - restore_cache:
          key: v1-bower-components-{{ checksum "bower.json" }}
      - run:
          name: Install Bower
          command: sudo npm install -g bower
      - run:
          name: Yarn Install
          command: yarn install --non-interactive
      - run:
          name: Bower Install
          command: bower install
      - save_cache:
          key: v1-node-modules-{{ checksum "yarn.lock" }}
          paths:
            - ~/gitzoom-web/node_modules
      - save_cache:
          key: v1-bower-components-{{ checksum "bower.json" }}
          paths:
            - ~/gitzoom-web/bower_components

  run_tests:
    <<: *defaults
    steps:
      - run:
          <<: *save_sha
      - restore_cache:
          key: v1-repo-{{ checksum ".circle-sha" }}
      - restore_cache:
          key: v1-node-modules-{{ checksum "yarn.lock" }}
      - restore_cache:
          key: v1-bower-components-{{ checksum "bower.json" }}
      - run: echo 'export PATH=~/gitzoom-web/node_modules/.bin:$PATH' >> $BASH_ENV
      - run:
          name: Run Tests
          command: JOBS=2 yarn test

  deploy_production:
    <<: *defaults
    steps:
      - run:
          <<: *save_sha
      - restore_cache:
          key: v1-repo-{{ checksum ".circle-sha" }}
      - restore_cache:
          key: v1-node-modules-{{ checksum "yarn.lock" }}
      - restore_cache:
          key: v1-bower-components-{{ checksum "bower.json" }}
      - run: echo 'export PATH=~/gitzoom-web/node_modules/.bin:$PATH' >> $BASH_ENV
      - run:
          name: Deploy Production
          command: ember deploy production

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - checkout_code:
          filters:
            tags:
              only: /.*/
      - install_dependencies:
          requires:
            - checkout_code
          filters:
            tags:
              only: /.*/
      - run_tests:
          requires:
            - install_dependencies
          filters:
            tags:
              only: /.*/
      - deploy_production:
          requires:
            - run_tests
          filters:
            tags:
              only: /v[0-9]+\.[0-9]+\.[0-9]+/
            branches:
              ignore: /.*/
